version: '3.1'

services:
  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
  web:
    image: docker-aiohttp-hello-world:latest
    command: python app.py
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo
